#FROM openhab/openhab:2.4.0-debian
FROM openhab/openhab:3.2.0
ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    ipmitool libfreeipmi-dev  && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
