FROM openhab/openhab:2.4.0-amd64-debian
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
    ipmitool libfreeipmi-dev  && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
