# This file was generated by go2nix.
with import <nixpkgs>{};

buildGoPackage rec {
  name = "gogs-${version}";
  version = "20161016-${stdenv.lib.strings.substring 0 7 rev}";
  rev = "6bcff7828f117af8d51285ce3acba01a7e40a867";

  goPackagePath = "github.com/gogits/gogs";

  buildInputs = [ sqlite git ];

  src = fetchgit {
    inherit rev;
    url = "https://github.com/gogits/gogs";
    sha256 = "1arnqgrs6pwz1yagbmvy70amkhch80mi2h55l2kpnnr7xdj36dxh";
  };

  buildFlags = [ "-tags sqlite" ];
  goDeps = ./deps.nix;

  # Copy supporing files
  postInstall = ''
    mkdir -p $bin/
    cp -r $src/templates/ $bin/bin
    cp -r $src/public/ $bin/bin
  '';
}

