# This file was mostly generated by go2nix.
[
  # Manual add of sqlite driver
  {
    goPackagePath = "github.com/mattn/go-sqlite3";
    fetch = {
      type = "git";
      url = "https://github.com/mattn/go-sqlite3";
      rev = "cde7293c72308f3cc5b57bfa65e162fb868470d8";
      sha256 = "1qw5dsb64qbr77hfcz1wjrgcvki19889h8r7hhzwibvsgm05gamb";
    };
  }
  {
    goPackagePath = "github.com/Unknwon/cae";
    fetch = {
      type = "git";
      url = "https://github.com/Unknwon/cae";
      rev = "c6aac99ea2cae2ebaf23f26f76b04fe3fcfc9f8c";
      sha256 = "0j6l1fcs6gp4qw6b9w3pg9fgah18lh1hanfz5y64r6ks244v3l7s";
    };
  }
  {
    goPackagePath = "github.com/Unknwon/com";
    fetch = {
      type = "git";
      url = "https://github.com/Unknwon/com";
      rev = "28b053d5a2923b87ce8c5a08f3af779894a72758";
      sha256 = "09i9slj4zbsqmwkkx9bqi7cgpv6hqby6r98l6qx1wag89qijybz2";
    };
  }
  {
    goPackagePath = "github.com/Unknwon/i18n";
    fetch = {
      type = "git";
      url = "https://github.com/Unknwon/i18n";
      rev = "39d6f2727e0698b1021ceb6a77c1801aa92e7d5d";
      sha256 = "1f4s9srdaqw2yqgc3d76vww3glbwka2f5q4zrwn8bb66kcazbfb7";
    };
  }
  {
    goPackagePath = "github.com/Unknwon/paginater";
    fetch = {
      type = "git";
      url = "https://github.com/Unknwon/paginater";
      rev = "7748a72e01415173a27d79866b984328e7b0c12b";
      sha256 = "0ighsa75ixgx6c4hc397c06lapf0pz50cj3cgkdvssp9an38kw2c";
    };
  }
  {
    goPackagePath = "github.com/bradfitz/gomemcache";
    fetch = {
      type = "git";
      url = "https://github.com/bradfitz/gomemcache";
      rev = "fb1f79c6b65acda83063cbc69f6bba1522558bfc";
      sha256 = "0mq5rn07bbpy2yla7hassrmj966p6r7ffbf9w41l31yy0fc07i68";
    };
  }
  {
    goPackagePath = "github.com/go-macaron/binding";
    fetch = {
      type = "git";
      url = "https://github.com/go-macaron/binding";
      rev = "9440f336b443056c90d7d448a0a55ad8c7599880";
      sha256 = "0g3ya3h8vjaykgp1npdxbizcf8kzv4m47vymcsq06vpihrfhbvg7";
    };
  }
  {
    goPackagePath = "github.com/go-macaron/cache";
    fetch = {
      type = "git";
      url = "https://github.com/go-macaron/cache";
      rev = "56173531277692bc2925924d51fda1cd0a6b8178";
      sha256 = "1116a22wm43q2l54nnycgli90kix787j20mpgya9qb6xnglcck59";
    };
  }
  {
    goPackagePath = "github.com/go-macaron/captcha";
    fetch = {
      type = "git";
      url = "https://github.com/go-macaron/captcha";
      rev = "8aa5919789ab301e865595eb4b1114d6b9847deb";
      sha256 = "0wdihxbl7yw4wg2x0wb09kv9swfpr5j06wsj4hxn3xcbpqi9viwm";
    };
  }
  {
    goPackagePath = "github.com/go-macaron/csrf";
    fetch = {
      type = "git";
      url = "https://github.com/go-macaron/csrf";
      rev = "6a9a7df172cc1fcd81e4585f44b09200b6087cc0";
      sha256 = "173da2hl9fcfgkn0nv1ws3pr0gyyp88amhj2bfk4414k5a3r0nsa";
    };
  }
  {
    goPackagePath = "github.com/go-macaron/gzip";
    fetch = {
      type = "git";
      url = "https://github.com/go-macaron/gzip";
      rev = "cad1c6580a07c56f5f6bc52d66002a05985c5854";
      sha256 = "12mq3dd1vd0jbi80fxab4ysmipbz9zhbm9nw6y6a6bw3byc8w4jf";
    };
  }
  {
    goPackagePath = "github.com/go-macaron/i18n";
    fetch = {
      type = "git";
      url = "https://github.com/go-macaron/i18n";
      rev = "ef57533c3b0fc2d8581deda14937e52f11a203ab";
      sha256 = "1nkrcnpjl3x6fhjss2vp29mnvam20vpvxvxpfg1zspi1rjmpyhqy";
    };
  }
  {
    goPackagePath = "github.com/go-macaron/inject";
    fetch = {
      type = "git";
      url = "https://github.com/go-macaron/inject";
      rev = "d8a0b8677191f4380287cfebd08e462217bac7ad";
      sha256 = "0p47pz699xhmi8yxhahvrpai9r49rqap5ckwmz1dlkrnh3zwhrhh";
    };
  }
  {
    goPackagePath = "github.com/go-macaron/session";
    fetch = {
      type = "git";
      url = "https://github.com/go-macaron/session";
      rev = "66031fcb37a0fff002a1f028eb0b3a815c78306b";
      sha256 = "1prrfv8xdlyxrdbagbqzjkx69x74hjzif5ki4lzl2y6fk3nb0cd5";
    };
  }
  {
    goPackagePath = "github.com/go-macaron/toolbox";
    fetch = {
      type = "git";
      url = "https://github.com/go-macaron/toolbox";
      rev = "99a42f20e9e88daec5c0d7beb4e7eac134680ab0";
      sha256 = "0r6ksiqzrii7b9vv8daz68044pyifsxmpz48m6h8m6l3h9ygz8cx";
    };
  }
  {
    goPackagePath = "github.com/go-sql-driver/mysql";
    fetch = {
      type = "git";
      url = "https://github.com/go-sql-driver/mysql";
      rev = "ce924a41eea897745442daaa1739089b0f3f561d";
      sha256 = "0k83c83v42xqy7hnshz96naf1in1c0qviwkxzgq1kgcn9g39mmha";
    };
  }
  {
    goPackagePath = "github.com/go-xorm/builder";
    fetch = {
      type = "git";
      url = "https://github.com/go-xorm/builder";
      rev = "cd42e8337f3031e737c3f415b6354793cf30f1c9";
      sha256 = "0h8s2p4w3gqmy4myvjmi3893ikkqzqrkqr3igq5af1vmjjk3b8ck";
    };
  }
  {
    goPackagePath = "github.com/go-xorm/core";
    fetch = {
      type = "git";
      url = "https://github.com/go-xorm/core";
      rev = "2ec3936f8a8a3fb6397c6c10185acffa87488534";
      sha256 = "0qxffvldhvdqsywk62yvsa3r8fgys6afw1jzl304cfmxcgj2wd3x";
    };
  }
  {
    goPackagePath = "github.com/go-xorm/xorm";
    fetch = {
      type = "git";
      url = "https://github.com/go-xorm/xorm";
      rev = "2b4faaaeabd118dfa541e751564004db98a6e995";
      sha256 = "06ixdqaq7il0zsn8ynk5dlsssx9jxbbakf4ima9lblsq7m605cc1";
    };
  }
  {
    goPackagePath = "github.com/gogits/chardet";
    fetch = {
      type = "git";
      url = "https://github.com/gogits/chardet";
      rev = "2404f777256163ea3eadb273dada5dcb037993c0";
      sha256 = "1dki2pqhnzcmzlqrq4d4jwknnjxm82xqnmizjjdblb6h98ans1cd";
    };
  }
  {
    goPackagePath = "github.com/gogits/cron";
    fetch = {
      type = "git";
      url = "https://github.com/gogits/cron";
      rev = "7f3990acf1833faa5ebd0e86f0a4c72a4b5eba3c";
      sha256 = "0y7z62g727pygnm5y1jp4i8izz4kzrnih8ihapxhin0isbfd3b6y";
    };
  }
  {
    goPackagePath = "github.com/gogits/git-module";
    fetch = {
      type = "git";
      url = "https://github.com/gogits/git-module";
      rev = "b3009dc4f5842cf9e2e80fef1e125e79c38e4949";
      sha256 = "1f5mms15hknnj17nvb5dwwk8fcm8a9msy9qdjvkplihxgaqm0amz";
    };
  }
  {
    goPackagePath = "github.com/gogits/go-gogs-client";
    fetch = {
      type = "git";
      url = "https://github.com/gogits/go-gogs-client";
      rev = "d8aff570fa22d4e38954c753ec8b21862239b31d";
      sha256 = "07gmvvljd48jwpkgsqlcp19rphn7ybcd4hzf7zahhl4dd4b8p4p3";
    };
  }
  {
    goPackagePath = "github.com/issue9/identicon";
    fetch = {
      type = "git";
      url = "https://github.com/issue9/identicon";
      rev = "d36b54562f4cf70c83653e13dc95c220c79ef521";
      sha256 = "0y82b3gq8rpqglvf3lsqhgp5djfdammwd1w24k3i97iqls0rch7l";
    };
  }
  {
    goPackagePath = "github.com/jaytaylor/html2text";
    fetch = {
      type = "git";
      url = "https://github.com/jaytaylor/html2text";
      rev = "8fb95d837f7d6db1913fecfd7bcc5333e6499596";
      sha256 = "0pzyidlp5jmzl5smhr9f8a81qpfls80j5m7156b032fvyvjwanlr";
    };
  }
  {
    goPackagePath = "github.com/klauspost/compress";
    fetch = {
      type = "git";
      url = "https://github.com/klauspost/compress";
      rev = "8df558b6cb6f9b445f9586446cfe7223e7d8bd6b";
      sha256 = "0ihwdk39414kaaa3nhcf1s4k8xdii20p7sxxjqkfd250s3jnql0y";
    };
  }
  {
    goPackagePath = "github.com/klauspost/cpuid";
    fetch = {
      type = "git";
      url = "https://github.com/klauspost/cpuid";
      rev = "09cded8978dc9e80714c4d85b0322337b0a1e5e0";
      sha256 = "05l8pfch0gvxh0khapwxhsk4xajn40vbjr360n49vh2z5531v2xq";
    };
  }
  {
    goPackagePath = "github.com/klauspost/crc32";
    fetch = {
      type = "git";
      url = "https://github.com/klauspost/crc32";
      rev = "cb6bfca970f6908083f26f39a79009d608efd5cd";
      sha256 = "0q4yr4isgmph1yf1vq527lpmid7vqv56q7vxh3gkp5679fb90q6n";
    };
  }
  {
    goPackagePath = "github.com/lib/pq";
    fetch = {
      type = "git";
      url = "https://github.com/lib/pq";
      rev = "ae8357db35d721c58dcdc911318b55bef6b1b001";
      sha256 = "16pqxlfjkh9ldpypw2ipqr8srwdmgnmb5j7wjkligkdxzvmbp7gx";
    };
  }
  {
    goPackagePath = "github.com/mcuadros/go-version";
    fetch = {
      type = "git";
      url = "https://github.com/mcuadros/go-version";
      rev = "d52711f8d6bea8dc01efafdb68ad95a4e2606630";
      sha256 = "08ps27vvn77jhrnks8p8mx5cwgb1ikhaddcnrpgpz7aq905a5kzn";
    };
  }
  {
    goPackagePath = "github.com/microcosm-cc/bluemonday";
    fetch = {
      type = "git";
      url = "https://github.com/microcosm-cc/bluemonday";
      rev = "f77f16ffc87a6a58814e64ae72d55f9c41374e6d";
      sha256 = "0pfm0pn39c07pp06gy8yr9jyq5nqhminsxh8j1dhl96rzrp0wic6";
    };
  }
  {
    goPackagePath = "github.com/nfnt/resize";
    fetch = {
      type = "git";
      url = "https://github.com/nfnt/resize";
      rev = "891127d8d1b52734debe1b3c3d7e747502b6c366";
      sha256 = "08lg2v4s1iyzqja7xb69d57gpz1y43yqfwv7i4fa7a06m595r9iw";
    };
  }
  {
    goPackagePath = "github.com/russross/blackfriday";
    fetch = {
      type = "git";
      url = "https://github.com/russross/blackfriday";
      rev = "5f33e7b7878355cd2b7e6b8eefc48a5472c69f70";
      sha256 = "0d7faqxrxvh8hwc1r8gbasgmr8x5blxvzciwspir2yafjfbqy87k";
    };
  }
  {
    goPackagePath = "github.com/satori/go.uuid";
    fetch = {
      type = "git";
      url = "https://github.com/satori/go.uuid";
      rev = "b061729afc07e77a8aa4fad0a2fd840958f1942a";
      sha256 = "0q87n5an7ha2d8kl6gn9wi41rq0whsxq68w5x3nxz7w9vgkfnq1k";
    };
  }
  {
    goPackagePath = "github.com/sergi/go-diff";
    fetch = {
      type = "git";
      url = "https://github.com/sergi/go-diff";
      rev = "ff694a8a530c929006f311ff29b669d36725dba8";
      sha256 = "1r3wc8la11pxbrbc7ixqfmrpvx2wj3bh70grl7shdy1rr794xp5g";
    };
  }
  {
    goPackagePath = "github.com/shurcooL/sanitized_anchor_name";
    fetch = {
      type = "git";
      url = "https://github.com/shurcooL/sanitized_anchor_name";
      rev = "1dba4b3954bc059efc3991ec364f9f9a35f597d2";
      sha256 = "0pwap8lp79pldd95a1qi3xhlsa17m8zddpgc5jzvk6d1cjpsm6qg";
    };
  }
  {
    goPackagePath = "github.com/strk/go-libravatar";
    fetch = {
      type = "git";
      url = "https://github.com/strk/go-libravatar";
      rev = "5eed7bff870ae19ef51c5773dbc8f3e9fcbd0982";
      sha256 = "1pjb7a4v42dg7y3j880qv20il77fq0cqwfsl9pz7ywi5rmgfnq6v";
    };
  }
  {
    goPackagePath = "github.com/urfave/cli";
    fetch = {
      type = "git";
      url = "https://github.com/urfave/cli";
      rev = "3eb41f1bb122ac7535cc7b32db6b78b541879726";
      sha256 = "17gh7093aawh6wv49smyqlwq3z58fysw2d1fblzylly35qxf5md5";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "9477e0b78b9ac3d0b03822fd95422e2fe07627cd";
      sha256 = "1qcqai6nf1q50z9ga7r4ljnrh1qz49kwlcqpri4bknx732lqq0v5";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "4bb47a1098b37d69980d96237e2ae4ff56bb5a95";
      sha256 = "0j77z5l8dp66q3pqcca23iqv1bjdqmmqc16kvvw5ix9xbwx4vzhf";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "a8b38433e35b65ba247bb267317037dee1b70cea";
      sha256 = "08jm5j4zpmc93aa7p992crm10li3v68gz01vqariph0adnmh8gc8";
    };
  }
  {
    goPackagePath = "gopkg.in/asn1-ber.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/asn1-ber.v1";
      rev = "4e86f4367175e39f69d9358a5f17b4dda270378d";
      sha256 = "13p8s74kzklb5lklfpxwxb78rknihawv1civ4s9bfqx565010fwk";
    };
  }
  {
    goPackagePath = "gopkg.in/bufio.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/bufio.v1";
      rev = "567b2bfa514e796916c4747494d6ff5132a1dfce";
      sha256 = "1z5pj778hdianlfj14p0d67g69v4gc2kvn6jg27z5jf75a88l19b";
    };
  }
  {
    goPackagePath = "gopkg.in/editorconfig/editorconfig-core-go.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/editorconfig/editorconfig-core-go.v1";
      rev = "a872f05c2e34b37b567401384d202aff11ba06d4";
      sha256 = "17mc7rm0fl5vi7ky95c2bd7c8ck0ms5bghzmgx9qk7x1zrw91335";
    };
  }
  {
    goPackagePath = "gopkg.in/gomail.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/gomail.v2";
      rev = "81ebce5c23dfd25c6c67194b37d3dd3f338c98b1";
      sha256 = "0zdykrv5s19lnq0g49p6njldy4cpk4g161vyjafiw7f84h8r28mc";
    };
  }
  {
    goPackagePath = "gopkg.in/ini.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/ini.v1";
      rev = "6e4869b434bd001f6983749881c7ead3545887d8";
      sha256 = "1w7qcl0k7bsp6871vr8mbli09imd67qqq1vbvpll33d2vw12wmva";
    };
  }
  {
    goPackagePath = "gopkg.in/ldap.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/ldap.v2";
      rev = "d0a5ced67b4dc310b9158d63a2c6f9c5ec13f105";
      sha256 = "02pgng2m8bfdh7471mjd6g19h53448hlsnl8l7jv9hm8mh1gp7jm";
    };
  }
  {
    goPackagePath = "gopkg.in/macaron.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/macaron.v1";
      rev = "4974334b10dbb6f5c0e17f4c10555ff050a16329";
      sha256 = "0jryd9xah6571xpn03i59wiziiz0w6v2dwda202y8y2yrjdxnzlp";
    };
  }
  {
    goPackagePath = "gopkg.in/redis.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/redis.v2";
      rev = "e6179049628164864e6e84e973cfb56335748dea";
      sha256 = "02hifpgak39y39lbn7v2ybbpk3rmb8nvmb3h3490frr8s4pfkb8h";
    };
  }
]
