# This file was generated by https://github.com/kamilchm/go2nix v1.2.0
with import <nixpkgs>{};

buildGoPackage rec {
  name = "gogs-unstable-${version}";
  version = "2017-06-08";
  rev = "7b85ee4954f77944a4c8088c6ad8117f26d28e05";

  goPackagePath = "github.com/gogits/gogs";
  buildInputs = [ sqlite git ];
  buildFlags = [ "-tags sqlite" ];

  src = fetchgit {
    inherit rev;
    url = "https://github.com/gogits/gogs";
    sha256 = "0jhpyxlswk28zwzkf0r2dbvm4xws1g8f3hz3zh9d1qa19ymhkz3c";
  };

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
